11 create wireframe
nittee/Iskrambol pull request #14
Opened 2024-07-28 04:43 UTC by Serv08

2024-07-28 23:57 UTC, jiroblea requested changes
suggestions for possible improvements were commented. Thank you!

2024-07-28 23:57 UTC, jiroblea commented on wireframe/v1_wireframe.drawio
I think that wireframe/ directory should be inside the docs/ directory.

2024-07-28 23:57 UTC, jiroblea commented on wireframe/v1_wireframe.png
### suggestions for possible improvements:

- the "GAME MODES" button can be renamed as "PLAY", then the player can choose which game mode they prefer to play.
- "CAMPAIGN" is a game mode, so it should be inside of the "GAME MODES". It can also minimize the screen or pages for the player to navigate.
- "NEW CAMPAIGN", "CONTINUE CAMPAIGN", "MULTIPLAYER", "CHALLENGE", and "PUZZLE" can be the game modes inside the game mode screen after pressing "PLAY" button.
- we should name each screen/page to distinguish them easily.

### good things I noticed

- the multiplayer mode screen is fine for now
- the back button is a nice touch
- the game being in full screen mode is great

2024-07-31 17:44 UTC, Serv08 commented on wireframe/v1_wireframe.png
Thanks for the suggestion and apologize for the late response.

For simplicity, I suggest "CAMPAIGN" to be renamed as "PLAY". When the user chose "PLAY", there would be no further sub menu such as choosing between "CONTINUE" or "NEW GAME"; simply starts at the last progress directly. This should be acceptable for lesser screen navigation and more gameplay time upon opening the app.

On the other hand, "GAME MODES" sub menu would still remain the same but can be renamed as "MODES" or "MORE".

I appreciate your suggestion on pointing out the naming for wireframe pages.

2024-08-04 08:07 UTC, ecisip reviewed
Hello, I apologize for the late response/review. I'm still trying to study not only the development process but this very review system in git itself lol.

- I think it is better and more intuitive if the "return" button is on the upper left instead of lower left. This is especially true considering we are likely putting the keyboard on the lower part of the screen (imagine accidentally clicking the back button while you type lol).
- I added a "?" button in the upper right corner of the screen. The "?" button shows the mechanics for the game (may be for a specifiic gamemode or all gamemodes). 
- I also added a "pause" button, also located at the upper right corner. This button is used in-game.
- I tried to formulate the "play screen" too, notes are in the wireframe file

Here is a photo of the wireframe file with my sugggestions
![v1_wireframe-wireframes](https://github.com/user-attachments/assets/df584e8e-b0f2-4ff6-97a7-919db9c42319)

2024-10-15 05:39 UTC, jiroblea approved these changes
LGTM

2024-10-15 06:10 UTC, merged