Merged '29 pause button pop up' branch to development
nittee/Iskrambol pull request #30
Opened 2024-12-21 13:57 UTC by jiroblea

Developed:
- working pause button
- UI of pause popup
- working buttons of pause popup

Please see the image:
![image](https://github.com/user-attachments/assets/bee46539-4f41-4e04-8929-ddcc668f50d4)

2024-12-21 15:50 UTC, Serv08 requested changes
Fix settings' back button from pause window

2024-12-21 15:50 UTC, Serv08 commented on iskrambol/playscreen.kv
back button in Settings from Pause window returns to main menu screen instead of Pause window

2024-12-21 18:06 UTC, jiroblea commented
> Fix settings' back button from pause window

That should be possible. We should open another issue for that.

2024-12-22 02:06 UTC, Serv08 commented
> > Fix settings' back button from pause window
> 
> That should be possible. We should open another issue for that.

ok. Let's stick with that

2024-12-22 02:07 UTC, Serv08 approved these changes

2024-12-22 02:08 UTC, merged